sudo: required
services:
    - docker

before_install:
    - docker build -t michalmatuszek/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true michalmatuszek/react-test npm test

after_success:
    - docker build -t michalmatuszek/multi-client ./client
    - docker build -t michalmatuszek/multi-nginx ./nginx
    - docker build -t michalmatuszek/multi-server ./server
    - docker build -t michalmatuszek/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those image and push them to docker hub
    - docker push michalmatuszek/multi-client
    - docker push michalmatuszek/multi-nginx
    - docker push michalmatuszek/multi-server
    - docker push michalmatuszek/multi-worker


